### ISSUE TITLE
🐛 Regressors censor `threshold` should be `thresholds`

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC_GUI#114]
### Describe the bug

Censor thresholds are being set by the GUI like

```YAML
Censor:
  threshold:
    type: FD_P
    value: 0.2
```

when they should be like

```YAML
Censor:
  thresholds:
    - type: FD_P
      value: 0.2
```

### To reproduce

Create a regressor with censoring and download the config

### Expected behavior

The config generates the correct syntax

### Acceptance criteria

- [x] The config generates the correct syntax:
    - [x] key = 'thresholds'
    - [x] value = list of dicts
