### ISSUE TITLE
🐛 [User-reported Bug] home page / tabs / order of processing / nuisance regression / how to folk

### ISSUE THREAD

**Issue by TingsterX** [FCP-INDI/C-PAC_GUI#131]
### Describe the bug

C-PAC GUI

- It seems that GUI would save the config whoever used the GUI most recently. When open https://fcp-indi.github.io/C-PAC_GUI/, it showed a lot of config “Default (2), Default (3), ... ” which were created by someone else earlier. If the earlier user duplicated the default one but changed something, the name is still “Default something”. This could be confusing to the new user. It would be good to have a clean Home page with only “Default” config showing there. 

- The order of Tabs. Is the order of Tab somewhat reflect the order of the processing? For example. currently, nuisance regression is at the relative end of the options. Does it mean that all the Tabs before nuisance regression will run before nuisance regression? If not, it's probably better to arrange tabs, for example, from minimal preprocessing, preprocessing, postprocessing, to post-analysis. 

- Time series extraction: It is not clear at which step the time series is extracted,e.g. after minimal preprocessing, after nuisance regression, etc.?

- Network centrality, ReHo, ALFF. Similar question, at which step these will be calculated?

- Longitudinal template. No document for this option. I guess it is for the anatomical image across sessions?

- Nuisance regression. 2-nuisance regression. What is the bandPass option here? Is it band-pass filtering on the regressor or just adds band-pass filtering to filter the data? Doesn’t matter if selected or not, it always shows as selected. 

- Nuisance regression - Regressor mask. No document for this option. are the options “csf_erosion_prop”, “csf_mask_erosion_mm”, “csf_erosion_mm” OR or AND? What does it mean “csf_erosion_prop”? Use the probability map to threshold the mask? Or it means that keep e.g. 0.6 proportion of a given tissue mask that defined in the earlier step? And, default 30mm for “GM_mask_erosion_mm” seems off, too big.

- How can we select folk GSR and noGSR in the GUI? If can’t do it in GUI, could we have a note in GUI to tell the user how to fold this option in the config?

Ting

### To reproduce

1. Go to https://fcp-indi.github.io/C-PAC_GUI/#/

### Expected behavior

clear document/note

### Acceptance criteria

clear document/note

### Screenshots

Some one left the configs there
![Screen Shot 2021-12-13 at 12 49 54 PM](https://user-images.githubusercontent.com/7852373/145862815-0c8e3906-505f-4be7-ad66-b8e581031473.png)

### Container platform

Docker

**Comment by shnizzedy** [comment]
There's a flowchart in the user documentation [here](https://fcp-indi.github.io/docs/latest/user/preprocessing) that shows the sequence of steps that C-PAC follows:

![C-PAC individual pipeline](https://fcp-indi.github.io/docs/latest/_static/flowcharts/pipeline-individual.svg)

**Comment by shnizzedy** [comment]
> Time series extraction: It is not clear at which step the time series is extracted,e.g. after minimal preprocessing, after nuisance regression, etc.?

After functional preprocessing is complete

**Comment by shnizzedy** [comment]
> Network centrality, ReHo, ALFF. Similar question, at which step these will be calculated?

Also after functional preprocessing (and anatomical to template registration and functional to template warp) is complete, and in parallel to each other

**Comment by shnizzedy** [comment]
> Longitudinal template. No document for this option. I guess it is for the anatomical image across sessions?

There is some (although not much beyond [![a flowchart](https://fcp-indi.github.io/docs/latest/_static/flowcharts/longitudinal.svg)](https://fcp-indi.github.io/docs/latest/_static/flowcharts/longitudinal.svg)) documentation at https://fcp-indi.github.io/docs/user/longitudinal and some [in the comments included in the default pipeline YAML](https://github.com/FCP-INDI/C-PAC/blob/a33dfe892ce3cd31d346f3c1ab032e7e91e4ba0f/dev/docker_data/default_pipeline.yml#L193-L225):

```YAML
longitudinal_template_generation:

  # If you have multiple T1w's, you can generate your own run-specific custom
  # T1w template to serve as an intermediate to the standard template for
  # anatomical registration.

  # This runs before the main pipeline as it requires multiple T1w sessions
  # at once.
  run: Off

  # Freesurfer longitudinal template algorithm using FSL FLIRT
  # Method to average the dataset at each iteration of the template creation
  # Options: median, mean or std
  average_method: median

  # Degree of freedom for FLIRT in the template creation
  # Options: 12 (affine), 9 (traditional), 7 (global rescale) or 6 (rigid body)
  dof: 12

  # Interpolation parameter for FLIRT in the template creation
  # Options: trilinear, nearestneighbour, sinc or spline
  interp: trilinear

  # Cost function for FLIRT in the template creation
  # Options: corratio, mutualinfo, normmi, normcorr, leastsq, labeldiff or bbr
  cost: corratio

  # Number of threads used for one run of the template generation algorithm
  thread_pool: 2

  # Threshold of transformation distance to consider that the loop converged
  # (-1 means numpy.finfo(np.float64).eps and is the default)
  convergence_threshold: -1
```

We intend to include those comments in the GUI, but [that work](#100) has not yet been completed.
